### ISSUE TITLE
Wrong connection method on client object.

### ISSUE THREAD

**Issue by nodgear** [axisiscool/koia#1]
`Property 'connect' does not exist on type 'Client'.`

from example code (running with node-ts) ~ line 25

**Comment by axisiscool** [comment]
The examples were written prior to making some breaking changes... the updated method should be: `<Client>.login('BOT_TOKEN');`

**Comment by nodgear** [comment]
> The examples were written prior to making some breaking changes... the updated method should be: `<Client>.login('BOT_TOKEN');`

Yeah, i figured by looking at the reference ~~god bless vscode~~
Did a pull request to readme #2
